[package]
name = "zz-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lib]

[[bin]]
name = "zz_cli"
path = "src/main.rs"

[dependencies]
env_logger.workspace = true
log.workspace = true
mimalloc.workspace = true
serde_json.workspace = true
zz-config.workspace = true
zz-daemon = { workspace = true, features = ["default"] }
zz-mux.workspace = true
zz-protocol.workspace = true
zz-terminal = { workspace = true, features = ["default"] }
zz-tui.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true
rustix = { workspace = true, features = ["fs", "net"] }

[target.'cfg(target_os = "linux")'.dependencies]
mimalloc = { workspace = true, features = ["no_thp"] }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Win32_System_Console"] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
