#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum TmuxOptionKind {
    String,
    Number,
    Flag,
    Choice,
    Colour,
    Style,
    Key,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct TmuxOptionMetadata {
    pub kind: TmuxOptionKind,
    pub description: &'static str,
    pub unit: &'static str,
    pub choices: &'static [&'static str],
}

pub(crate) fn tmux_option_metadata(name: &str) -> TmuxOptionMetadata {
    let (kind, description, unit, choices): (_, _, _, &'static [&'static str]) = match name {
        "backspace" => (
            TmuxOptionKind::Key,
            "The key to send for backspace.",
            "",
            &[],
        ),
        "buffer-limit" => (
            TmuxOptionKind::Number,
            "The maximum number of automatic buffers. When this is reached, the oldest buffer is deleted.",
            "",
            &[],
        ),
        "command-alias" => (
            TmuxOptionKind::String,
            "Array of command aliases. Each entry is an alias and a command separated by '='.",
            "",
            &[],
        ),
        "codepoint-widths" => (
            TmuxOptionKind::String,
            "Array of override widths for Unicode codepoints.",
            "",
            &[],
        ),
        "copy-command" => (
            TmuxOptionKind::String,
            "Shell command run when text is copied. If empty, no command is run.",
            "",
            &[],
        ),
        "cursor-colour" => (TmuxOptionKind::String, "Colour of the cursor.", "", &[]),
        "cursor-style" => (
            TmuxOptionKind::Choice,
            "Style of the cursor.",
            "",
            &[
                "default",
                "blinking-block",
                "block",
                "blinking-underline",
                "underline",
                "blinking-bar",
                "bar",
            ],
        ),
        "default-client-command" => (
            TmuxOptionKind::String,
            "Default command to run when tmux is run without a command.",
            "",
            &[],
        ),
        "default-terminal" => (
            TmuxOptionKind::String,
            "Default for the 'TERM' environment variable.",
            "",
            &[],
        ),
        "editor" => (TmuxOptionKind::String, "Editor run to edit files.", "", &[]),
        "escape-time" => (
            TmuxOptionKind::Number,
            "Time to wait before assuming a key is Escape.",
            "milliseconds",
            &[],
        ),
        "exit-empty" => (
            TmuxOptionKind::Flag,
            "Whether the server should exit if there are no sessions.",
            "",
            &[],
        ),
        "exit-unattached" => (
            TmuxOptionKind::Flag,
            "Whether the server should exit if there are no attached clients.",
            "",
            &[],
        ),
        "extended-keys" => (
            TmuxOptionKind::Choice,
            "Whether to request extended key sequences from terminals that support it.",
            "",
            &["off", "on", "always"],
        ),
        "extended-keys-format" => (
            TmuxOptionKind::Choice,
            "The format of emitted extended key sequences.",
            "",
            &["csi-u", "xterm"],
        ),
        "focus-events" => (
            TmuxOptionKind::Flag,
            "Whether to send focus events to applications.",
            "",
            &[],
        ),
        "get-clipboard" => (
            TmuxOptionKind::Choice,
            "When an application requests the clipboard, whether to ignore the request ('off'); respond with the newest buffer ('buffer'); request the clipboard from the most recently used terminal ('request'); or to request the clipboard, create a buffer, and send it to the application ('both').",
            "",
            &["off", "buffer", "request", "both"],
        ),
        "history-file" => (
            TmuxOptionKind::String,
            "Location of the command prompt history file. Empty does not write a history file.",
            "",
            &[],
        ),
        "input-buffer-size" => (
            TmuxOptionKind::Number,
            "Number of bytes accepted in a single input before dropping.",
            "",
            &[],
        ),
        "menu-style" => (TmuxOptionKind::Style, "Default style of menu.", "", &[]),
        "menu-selected-style" => (
            TmuxOptionKind::Style,
            "Default style of selected menu item.",
            "",
            &[],
        ),
        "menu-border-style" => (
            TmuxOptionKind::Style,
            "Default style of menu borders.",
            "",
            &[],
        ),
        "menu-border-lines" => (
            TmuxOptionKind::Choice,
            "Type of characters used to draw menu border lines. Some of these are only supported on terminals with UTF-8 support.",
            "",
            &[
                "single", "double", "heavy", "simple", "rounded", "padded", "none",
            ],
        ),
        "message-limit" => (
            TmuxOptionKind::Number,
            "Maximum number of server messages to keep.",
            "",
            &[],
        ),
        "prefix-timeout" => (
            TmuxOptionKind::Number,
            "The timeout for the prefix key if no subsequent key is pressed. Zero means disabled.",
            "milliseconds",
            &[],
        ),
        "prompt-history-limit" => (
            TmuxOptionKind::Number,
            "Maximum number of commands to keep in history.",
            "",
            &[],
        ),
        "set-clipboard" => (
            TmuxOptionKind::Choice,
            "Whether to attempt to set the system clipboard ('on' or 'external') and whether to allow applications to create paste buffers with an escape sequence ('on' only).",
            "",
            &["off", "external", "on"],
        ),
        "terminal-overrides" => (
            TmuxOptionKind::String,
            "List of terminal capabilities overrides.",
            "",
            &[],
        ),
        "terminal-features" => (
            TmuxOptionKind::String,
            "List of terminal features, used if they cannot be automatically detected.",
            "",
            &[],
        ),
        "theme" => (
            TmuxOptionKind::Choice,
            "Whether tmux should detect the terminal theme, use terminal ANSI colours, or force the light or dark theme.",
            "",
            &["detect", "terminal", "light", "dark"],
        ),
        "dark-theme-black" => (
            TmuxOptionKind::String,
            "Dark theme colour for black.",
            "",
            &[],
        ),
        "dark-theme-white" => (
            TmuxOptionKind::String,
            "Dark theme colour for white.",
            "",
            &[],
        ),
        "dark-theme-light-grey" => (
            TmuxOptionKind::String,
            "Dark theme colour for light grey.",
            "",
            &[],
        ),
        "dark-theme-dark-grey" => (
            TmuxOptionKind::String,
            "Dark theme colour for dark grey.",
            "",
            &[],
        ),
        "dark-theme-green" => (
            TmuxOptionKind::String,
            "Dark theme colour for green.",
            "",
            &[],
        ),
        "dark-theme-yellow" => (
            TmuxOptionKind::String,
            "Dark theme colour for yellow.",
            "",
            &[],
        ),
        "dark-theme-red" => (
            TmuxOptionKind::String,
            "Dark theme colour for red.",
            "",
            &[],
        ),
        "dark-theme-blue" => (
            TmuxOptionKind::String,
            "Dark theme colour for blue.",
            "",
            &[],
        ),
        "dark-theme-cyan" => (
            TmuxOptionKind::String,
            "Dark theme colour for cyan.",
            "",
            &[],
        ),
        "dark-theme-magenta" => (
            TmuxOptionKind::String,
            "Dark theme colour for magenta.",
            "",
            &[],
        ),
        "light-theme-black" => (
            TmuxOptionKind::String,
            "Light theme colour for black.",
            "",
            &[],
        ),
        "light-theme-white" => (
            TmuxOptionKind::String,
            "Light theme colour for white.",
            "",
            &[],
        ),
        "light-theme-light-grey" => (
            TmuxOptionKind::String,
            "Light theme colour for light grey.",
            "",
            &[],
        ),
        "light-theme-dark-grey" => (
            TmuxOptionKind::String,
            "Light theme colour for dark grey.",
            "",
            &[],
        ),
        "light-theme-green" => (
            TmuxOptionKind::String,
            "Light theme colour for green.",
            "",
            &[],
        ),
        "light-theme-yellow" => (
            TmuxOptionKind::String,
            "Light theme colour for yellow.",
            "",
            &[],
        ),
        "light-theme-red" => (
            TmuxOptionKind::String,
            "Light theme colour for red.",
            "",
            &[],
        ),
        "light-theme-blue" => (
            TmuxOptionKind::String,
            "Light theme colour for blue.",
            "",
            &[],
        ),
        "light-theme-cyan" => (
            TmuxOptionKind::String,
            "Light theme colour for cyan.",
            "",
            &[],
        ),
        "light-theme-magenta" => (
            TmuxOptionKind::String,
            "Light theme colour for magenta.",
            "",
            &[],
        ),
        "user-keys" => (
            TmuxOptionKind::String,
            "User key assignments. Each sequence in the list is translated into a key: 'User0', 'User1' and so on.",
            "",
            &[],
        ),
        "variation-selector-always-wide" => (
            TmuxOptionKind::Flag,
            "If the Unicode VS16 codepoint should always be treated as a wide character.",
            "",
            &[],
        ),
        "activity-action" => (
            TmuxOptionKind::Choice,
            "Action to take on an activity alert.",
            "",
            &["none", "any", "current", "other"],
        ),
        "assume-paste-time" => (
            TmuxOptionKind::Number,
            "Maximum time between input to assume it is pasting rather than typing.",
            "milliseconds",
            &[],
        ),
        "base-index" => (
            TmuxOptionKind::Number,
            "Default index of the first window in each session.",
            "",
            &[],
        ),
        "bell-action" => (
            TmuxOptionKind::Choice,
            "Action to take on a bell alert.",
            "",
            &["none", "any", "current", "other"],
        ),
        "default-command" => (
            TmuxOptionKind::String,
            "Default command to run in new panes. If empty, a shell is started.",
            "",
            &[],
        ),
        "default-shell" => (
            TmuxOptionKind::String,
            "Location of default shell.",
            "",
            &[],
        ),
        "default-size" => (
            TmuxOptionKind::String,
            "Initial size of new sessions.",
            "",
            &[],
        ),
        "destroy-unattached" => (
            TmuxOptionKind::Choice,
            "Whether to destroy sessions when they have no attached clients, or keep the last session whether in the group.",
            "",
            &["off", "on", "keep-last", "keep-group"],
        ),
        "detach-on-destroy" => (
            TmuxOptionKind::Choice,
            "Whether to detach when a session is destroyed, or switch the client to another session if any exist.",
            "",
            &["off", "on", "no-detached", "previous", "next"],
        ),
        "display-panes-active-colour" => (
            TmuxOptionKind::String,
            "Colour of the active pane for 'display-panes'.",
            "",
            &[],
        ),
        "display-panes-colour" => (
            TmuxOptionKind::String,
            "Colour of not active panes for 'display-panes'.",
            "",
            &[],
        ),
        "display-panes-format" => (
            TmuxOptionKind::String,
            "Format of text shown by 'display-panes', expanded for each pane.",
            "",
            &[],
        ),
        "display-panes-time" => (
            TmuxOptionKind::Number,
            "Time for which 'display-panes' should show pane numbers.",
            "milliseconds",
            &[],
        ),
        "display-time" => (
            TmuxOptionKind::Number,
            "Time for which status line messages should appear.",
            "milliseconds",
            &[],
        ),
        "focus-follows-mouse" => (
            TmuxOptionKind::Flag,
            "Whether moving the mouse into a pane selects it.",
            "",
            &[],
        ),
        "history-limit" => (
            TmuxOptionKind::Number,
            "Maximum number of lines to keep in the history for each pane. If changed, the new value applies only to new panes.",
            "lines",
            &[],
        ),
        "initial-repeat-time" => (
            TmuxOptionKind::Number,
            "Time to wait for a key binding to repeat the first time the key is pressed, if it is bound with the '-r' flag. Subsequent presses use the 'repeat-time' option.",
            "milliseconds",
            &[],
        ),
        "key-table" => (
            TmuxOptionKind::String,
            "Default key table. Key presses are first looked up in this table.",
            "",
            &[],
        ),
        "lock-after-time" => (
            TmuxOptionKind::Number,
            "Time after which a client is locked if not used.",
            "seconds",
            &[],
        ),
        "lock-command" => (
            TmuxOptionKind::String,
            "Shell command to run to lock a client.",
            "",
            &[],
        ),
        "message-command-style" => (
            TmuxOptionKind::Style,
            "Style of the command prompt when in command mode, if 'status-keys' is set to 'vi'.",
            "",
            &[],
        ),
        "message-format" => (
            TmuxOptionKind::String,
            "Format string for the prompt and message area. The '#{message}' placeholder is replaced with the content.",
            "",
            &[],
        ),
        "message-line" => (
            TmuxOptionKind::Choice,
            "Position (line) of messages and the command prompt.",
            "",
            &["0", "1", "2", "3", "4"],
        ),
        "message-style" => (
            TmuxOptionKind::Style,
            "Style of messages and the command prompt. A 'fill' attribute controls background clearing and a 'width' attribute (fixed or percentage) constrains the prompt area width.",
            "",
            &[],
        ),
        "mouse" => (
            TmuxOptionKind::Flag,
            "Whether the mouse is recognised and mouse key bindings are executed. Applications inside panes can use the mouse even when 'off'.",
            "",
            &[],
        ),
        "prefix" => (TmuxOptionKind::Key, "The prefix key.", "", &[]),
        "prefix2" => (TmuxOptionKind::Key, "A second prefix key.", "", &[]),
        "renumber-windows" => (
            TmuxOptionKind::Flag,
            "Whether windows are automatically renumbered rather than leaving gaps.",
            "",
            &[],
        ),
        "repeat-time" => (
            TmuxOptionKind::Number,
            "Time to wait for a key binding to repeat, if it is bound with the '-r' flag.",
            "milliseconds",
            &[],
        ),
        "set-titles" => (
            TmuxOptionKind::Flag,
            "Whether to set the terminal title, if supported.",
            "",
            &[],
        ),
        "set-titles-string" => (
            TmuxOptionKind::String,
            "Format of the terminal title to set.",
            "",
            &[],
        ),
        "silence-action" => (
            TmuxOptionKind::Choice,
            "Action to take on a silence alert.",
            "",
            &["none", "any", "current", "other"],
        ),
        "status" => (
            TmuxOptionKind::Choice,
            "Number of lines in the status line.",
            "",
            &["off", "on", "2", "3", "4", "5"],
        ),
        "status-bg" => (
            TmuxOptionKind::Colour,
            "Background colour of the status line. This option is deprecated, use 'status-style' instead.",
            "",
            &[],
        ),
        "status-fg" => (
            TmuxOptionKind::Colour,
            "Foreground colour of the status line. This option is deprecated, use 'status-style' instead.",
            "",
            &[],
        ),
        "status-format" => (
            TmuxOptionKind::String,
            "Formats for the status lines. Each array member is the format for one status line. The default status line is made up of several components which may be configured individually with other options such as 'status-left'.",
            "",
            &[],
        ),
        "status-interval" => (
            TmuxOptionKind::Number,
            "Number of seconds between status line updates.",
            "seconds",
            &[],
        ),
        "status-justify" => (
            TmuxOptionKind::Choice,
            "Position of the window list in the status line.",
            "",
            &["left", "centre", "right", "absolute-centre"],
        ),
        "status-keys" => (
            TmuxOptionKind::Choice,
            "Key set to use at the command prompt.",
            "",
            &["emacs", "vi"],
        ),
        "status-left" => (
            TmuxOptionKind::String,
            "Contents of the left side of the status line.",
            "",
            &[],
        ),
        "status-left-length" => (
            TmuxOptionKind::Number,
            "Maximum width of the left side of the status line.",
            "",
            &[],
        ),
        "status-left-style" => (
            TmuxOptionKind::Style,
            "Style of the left side of the status line.",
            "",
            &[],
        ),
        "status-position" => (
            TmuxOptionKind::Choice,
            "Position of the status line.",
            "",
            &["top", "bottom"],
        ),
        "status-right" => (
            TmuxOptionKind::String,
            "Contents of the right side of the status line.",
            "",
            &[],
        ),
        "status-right-length" => (
            TmuxOptionKind::Number,
            "Maximum width of the right side of the status line.",
            "",
            &[],
        ),
        "status-right-style" => (
            TmuxOptionKind::Style,
            "Style of the right side of the status line.",
            "",
            &[],
        ),
        "status-style" => (TmuxOptionKind::Style, "Style of the status line.", "", &[]),
        "pane-status-current-style" => (
            TmuxOptionKind::Style,
            "Style of the current pane in the status line.",
            "",
            &[],
        ),
        "pane-status-style" => (
            TmuxOptionKind::Style,
            "Style of panes in the status line, except the current pane.",
            "",
            &[],
        ),
        "prompt-cursor-colour" => (
            TmuxOptionKind::String,
            "Colour of the cursor when in the command prompt.",
            "",
            &[],
        ),
        "prompt-command-cursor-colour" => (
            TmuxOptionKind::String,
            "Colour of the cursor in the command prompt when in command mode, if 'status-keys' is set to 'vi'.",
            "",
            &[],
        ),
        "prompt-cursor-style" => (
            TmuxOptionKind::Choice,
            "Style of the cursor when in the command prompt.",
            "",
            &[
                "default",
                "blinking-block",
                "block",
                "blinking-underline",
                "underline",
                "blinking-bar",
                "bar",
            ],
        ),
        "prompt-command-cursor-style" => (
            TmuxOptionKind::Choice,
            "Style of the cursor in the command prompt when in command mode, if 'status-keys' is set to 'vi'.",
            "",
            &[
                "default",
                "blinking-block",
                "block",
                "blinking-underline",
                "underline",
                "blinking-bar",
                "bar",
            ],
        ),
        "session-status-current-style" => (
            TmuxOptionKind::Style,
            "Style of the current session in the status line.",
            "",
            &[],
        ),
        "session-status-style" => (
            TmuxOptionKind::Style,
            "Style of sessions in the status line, except the current session.",
            "",
            &[],
        ),
        "update-environment" => (
            TmuxOptionKind::String,
            "List of environment variables to update in the session environment when a client is attached.",
            "",
            &[],
        ),
        "visual-activity" => (
            TmuxOptionKind::Choice,
            "How activity alerts should be shown: a message ('on'), a message and a bell ('both') or nothing ('off').",
            "",
            &["off", "on", "both"],
        ),
        "visual-bell" => (
            TmuxOptionKind::Choice,
            "How bell alerts should be shown: a message ('on'), a message and a bell ('both') or nothing ('off').",
            "",
            &["off", "on", "both"],
        ),
        "visual-silence" => (
            TmuxOptionKind::Choice,
            "How silence alerts should be shown: a message ('on'), a message and a bell ('both') or nothing ('off').",
            "",
            &["off", "on", "both"],
        ),
        "word-separators" => (
            TmuxOptionKind::String,
            "Characters considered to separate words.",
            "",
            &[],
        ),
        "aggressive-resize" => (
            TmuxOptionKind::Flag,
            "When 'window-size' is 'smallest', whether the maximum size of a window is the smallest attached session where it is the current window ('on') or the smallest session it is linked to ('off').",
            "",
            &[],
        ),
        "allow-passthrough" => (
            TmuxOptionKind::Choice,
            "Whether applications are allowed to use the escape sequence to bypass tmux. Can be 'off' (disallowed), 'on' (allowed if the pane is visible), or 'all' (allowed even if the pane is invisible).",
            "",
            &["off", "on", "all"],
        ),
        "allow-rename" => (
            TmuxOptionKind::Flag,
            "Whether applications are allowed to use the escape sequence to rename windows.",
            "",
            &[],
        ),
        "allow-set-title" => (
            TmuxOptionKind::Flag,
            "Whether applications are allowed to use the escape sequence to set the pane title.",
            "",
            &[],
        ),
        "alternate-screen" => (
            TmuxOptionKind::Flag,
            "Whether applications are allowed to use the alternate screen.",
            "",
            &[],
        ),
        "automatic-rename" => (
            TmuxOptionKind::Flag,
            "Whether windows are automatically renamed.",
            "",
            &[],
        ),
        "automatic-rename-format" => (
            TmuxOptionKind::String,
            "Format used to automatically rename windows.",
            "",
            &[],
        ),
        "clock-mode-colour" => (
            TmuxOptionKind::String,
            "Colour of the clock in clock mode.",
            "",
            &[],
        ),
        "clock-mode-style" => (
            TmuxOptionKind::Choice,
            "Time format of the clock in clock mode.",
            "",
            &["12", "24", "12-with-seconds", "24-with-seconds"],
        ),
        "copy-mode-match-style" => (
            TmuxOptionKind::Style,
            "Style of search matches in copy mode.",
            "",
            &[],
        ),
        "copy-mode-current-match-style" => (
            TmuxOptionKind::Style,
            "Style of the current search match in copy mode.",
            "",
            &[],
        ),
        "copy-mode-mark-style" => (
            TmuxOptionKind::Style,
            "Style of the marked line in copy mode.",
            "",
            &[],
        ),
        "copy-mode-position-format" => (
            TmuxOptionKind::String,
            "Format of the position indicator in copy mode.",
            "",
            &[],
        ),
        "copy-mode-position-style" => (
            TmuxOptionKind::Style,
            "Style of position indicator in copy mode.",
            "",
            &[],
        ),
        "copy-mode-selection-style" => (
            TmuxOptionKind::Style,
            "Style of selection in copy mode.",
            "",
            &[],
        ),
        "copy-mode-current-line-number-style" => (
            TmuxOptionKind::Style,
            "Style of current line number in copy mode.",
            "",
            &[],
        ),
        "copy-mode-line-number-style" => (
            TmuxOptionKind::Style,
            "Style of line numbers in copy mode.",
            "",
            &[],
        ),
        "copy-mode-line-numbers" => (
            TmuxOptionKind::Choice,
            "Line number mode in copy mode.",
            "",
            &["off", "default", "absolute", "relative", "hybrid"],
        ),
        "fill-character" => (
            TmuxOptionKind::String,
            "Character used to fill unused parts of window.",
            "",
            &[],
        ),
        "main-pane-height" => (
            TmuxOptionKind::String,
            "Height of the main pane in the 'main-horizontal' layout. This may be a percentage, for example '10%'.",
            "",
            &[],
        ),
        "main-pane-width" => (
            TmuxOptionKind::String,
            "Width of the main pane in the 'main-vertical' layout. This may be a percentage, for example '10%'.",
            "",
            &[],
        ),
        "mode-keys" => (
            TmuxOptionKind::Choice,
            "Key set used in copy mode.",
            "",
            &["emacs", "vi"],
        ),
        "mode-style" => (
            TmuxOptionKind::Style,
            "Style of indicators and highlighting in modes.",
            "",
            &[],
        ),
        "monitor-activity" => (
            TmuxOptionKind::Flag,
            "Whether an alert is triggered by activity.",
            "",
            &[],
        ),
        "monitor-bell" => (
            TmuxOptionKind::Flag,
            "Whether an alert is triggered by a bell.",
            "",
            &[],
        ),
        "monitor-silence" => (
            TmuxOptionKind::Number,
            "Time after which an alert is triggered by silence. Zero means no alert.",
            "",
            &[],
        ),
        "other-pane-height" => (
            TmuxOptionKind::String,
            "Height of the other panes in the 'main-horizontal' layout. This may be a percentage, for example '10%'.",
            "",
            &[],
        ),
        "other-pane-width" => (
            TmuxOptionKind::String,
            "Height of the other panes in the 'main-vertical' layout. This may be a percentage, for example '10%'.",
            "",
            &[],
        ),
        "pane-active-border-style" => (
            TmuxOptionKind::Style,
            "Style of the active pane border.",
            "",
            &[],
        ),
        "pane-base-index" => (
            TmuxOptionKind::Number,
            "Index of the first pane in each window.",
            "",
            &[],
        ),
        "pane-border-format" => (
            TmuxOptionKind::String,
            "Format of text in the pane status lines.",
            "",
            &[],
        ),
        "pane-border-indicators" => (
            TmuxOptionKind::Choice,
            "Whether to indicate the active pane by colouring border or displaying arrow markers.",
            "",
            &["off", "colour", "arrows", "both"],
        ),
        "pane-border-lines" => (
            TmuxOptionKind::Choice,
            "Type of characters used to draw pane border lines. Some of these are only supported on terminals with UTF-8 support.",
            "",
            &[
                "single", "double", "heavy", "simple", "number", "spaces", "none",
            ],
        ),
        "pane-border-status" => (
            TmuxOptionKind::Choice,
            "Position of the pane status lines.",
            "",
            &["off", "top", "bottom", "top-floating", "bottom-floating"],
        ),
        "pane-border-style" => (
            TmuxOptionKind::Style,
            "Style of the pane status lines.",
            "",
            &[],
        ),
        "pane-colours" => (
            TmuxOptionKind::Colour,
            "The default colour palette for colours zero to 255.",
            "",
            &[],
        ),
        "pane-scrollbars" => (
            TmuxOptionKind::Choice,
            "Pane scrollbar state: off, on, modal, or auto-hide.",
            "",
            &["off", "modal", "on", "auto-hide"],
        ),
        "pane-scrollbars-timeout" => (
            TmuxOptionKind::Number,
            "Time before modal and auto-hide pane scrollbars disappear.",
            "milliseconds",
            &[],
        ),
        "pane-scrollbars-style" => (
            TmuxOptionKind::Style,
            "Style of the pane scrollbar.",
            "",
            &[],
        ),
        "pane-scrollbars-position" => (
            TmuxOptionKind::Choice,
            "Pane scrollbar position.",
            "",
            &["right", "left"],
        ),
        "popup-style" => (TmuxOptionKind::Style, "Default style of popups.", "", &[]),
        "popup-border-style" => (
            TmuxOptionKind::Style,
            "Default style of popup borders.",
            "",
            &[],
        ),
        "popup-border-lines" => (
            TmuxOptionKind::Choice,
            "Type of characters used to draw popup border lines. Some of these are only supported on terminals with UTF-8 support.",
            "",
            &[
                "single", "double", "heavy", "simple", "rounded", "padded", "none",
            ],
        ),
        "remain-on-exit" => (
            TmuxOptionKind::Choice,
            "Whether panes should remain ('on'), remain until a key is pressed ('key') or be automatically killed ('off' or 'failed') when the program inside exits.",
            "",
            &["off", "on", "failed", "key"],
        ),
        "remain-on-exit-format" => (
            TmuxOptionKind::String,
            "Message shown after the program in a pane has exited, if remain-on-exit is enabled.",
            "",
            &[],
        ),
        "scroll-on-clear" => (
            TmuxOptionKind::Flag,
            "Whether the contents of the screen should be scrolled intohistory when clearing the whole screen.",
            "",
            &[],
        ),
        "switch-mode-match-style" => (
            TmuxOptionKind::Style,
            "Style of matched characters in switch mode.",
            "",
            &[],
        ),
        "synchronize-panes" => (
            TmuxOptionKind::Flag,
            "Whether typing should be sent to all panes simultaneously.",
            "",
            &[],
        ),
        "tiled-layout-max-columns" => (
            TmuxOptionKind::Number,
            "Maximum number of columns in the 'tiled' layout. A value of 0 means no limit.",
            "",
            &[],
        ),
        "tree-mode-border-style" => (
            TmuxOptionKind::Style,
            "Style of borders in tree mode.",
            "",
            &[],
        ),
        "tree-mode-preview-format" => (
            TmuxOptionKind::String,
            "Format of the preview indicator in tree mode.",
            "",
            &[],
        ),
        "tree-mode-preview-style" => (
            TmuxOptionKind::Style,
            "Style of preview indicator in tree mode.",
            "",
            &[],
        ),
        "tree-mode-selection-style" => (
            TmuxOptionKind::Style,
            "Style of the selected line in tree mode.",
            "",
            &[],
        ),
        "window-active-style" => (
            TmuxOptionKind::Style,
            "Default style of the active pane.",
            "",
            &[],
        ),
        "window-pane-current-status-format" => (
            TmuxOptionKind::String,
            "Format of the current window pane in the status line.",
            "",
            &[],
        ),
        "window-pane-status-format" => (
            TmuxOptionKind::String,
            "Format of window panes in the status line, except the current pane.",
            "",
            &[],
        ),
        "window-size" => (
            TmuxOptionKind::Choice,
            "How window size is calculated. 'latest' uses the size of the most recently used client, 'largest' the largest client, 'smallest' the smallest client and 'manual' a size set by the 'resize-window' command.",
            "",
            &["largest", "smallest", "manual", "latest"],
        ),
        "window-style" => (
            TmuxOptionKind::Style,
            "Default style of panes that are not the active pane.",
            "",
            &[],
        ),
        "window-status-activity-style" => (
            TmuxOptionKind::Style,
            "Style of windows in the status line with an activity alert.",
            "",
            &[],
        ),
        "window-status-bell-style" => (
            TmuxOptionKind::Style,
            "Style of windows in the status line with a bell alert.",
            "",
            &[],
        ),
        "window-status-current-format" => (
            TmuxOptionKind::String,
            "Format of the current window in the status line.",
            "",
            &[],
        ),
        "window-status-current-style" => (
            TmuxOptionKind::Style,
            "Style of the current window in the status line.",
            "",
            &[],
        ),
        "window-status-format" => (
            TmuxOptionKind::String,
            "Format of windows in the status line, except the current window.",
            "",
            &[],
        ),
        "window-status-last-style" => (
            TmuxOptionKind::Style,
            "Style of the last window in the status line.",
            "",
            &[],
        ),
        "window-status-separator" => (
            TmuxOptionKind::String,
            "Separator between windows in the status line.",
            "",
            &[],
        ),
        "window-status-style" => (
            TmuxOptionKind::Style,
            "Style of windows in the status line, except the current and last windows.",
            "",
            &[],
        ),
        "wrap-search" => (
            TmuxOptionKind::Flag,
            "Whether searching in copy mode should wrap at the top or bottom.",
            "",
            &[],
        ),
        "xterm-keys" => (
            TmuxOptionKind::Flag,
            "Whether xterm-style function key sequences should be sent. This option is no longer used.",
            "",
            &[],
        ),
        _ => (
            TmuxOptionKind::String,
            "This option doesn't have a description.",
            "",
            &[],
        ),
    };
    TmuxOptionMetadata {
        kind,
        description,
        unit,
        choices,
    }
}
