[package]
name = "zpui-wgpu"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"

[lints.rust]
unexpected_cfgs = "allow"

[lints.clippy]
style = { level = "allow", priority = -1 }
dbg_macro = "deny"
todo = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"

[lib]
path = "src/zpui_wgpu.rs"
doctest = false

[features]
default = []
bench-support = ["zpui/bench-support", "dep:image"]
font-kit = ["dep:font-kit"]
test-support = ["zpui/test-support", "dep:image"]

[dependencies]
zpui.workspace = true
anyhow.workspace = true
bytemuck = "1"
naga = { version = "30.0.1", features = ["wgsl-in"] }
cosmic-text = "0.19.0"
etagere.workspace = true
itertools.workspace = true
image = { workspace = true, optional = true, features = [
    "bmp",
    "dds",
    "exr",
    "ff",
    "gif",
    "hdr",
    "ico",
    "jpeg",
    "png",
    "pnm",
    "qoi",
    "rayon",
    "tga",
    "tiff",
    "webp",
] }
log = { workspace = true, features = ["kv_unstable_serde", "serde"] }
parking_lot.workspace = true
profiling.workspace = true
raw-window-handle.workspace = true
smallvec = { workspace = true, features = ["union", "const_new"] }
swash.workspace = true
unicode-bidi.workspace = true
unicode-segmentation.workspace = true
wgpu.workspace = true

# Optional: only needed on platforms with multiple font sources (e.g. Linux)
# WARNING: If you change this, you must also publish a new version of zed-font-kit to crates.io
font-kit = { git = "https://github.com/zed-industries/font-kit", rev = "94b0f28166665e8fd2f53ff6d268a14955c82269", package = "zed-font-kit", version = "0.14.1-zed", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { version = "0.3", features = ["HtmlCanvasElement"] }
wgpu = { workspace = true, features = ["webgl"] }

[dev-dependencies]
criterion.workspace = true
zpui = { workspace = true, features = ["bench-support"] }
image = { workspace = true, features = [
    "bmp",
    "dds",
    "exr",
    "ff",
    "gif",
    "hdr",
    "ico",
    "jpeg",
    "png",
    "pnm",
    "qoi",
    "rayon",
    "tga",
    "tiff",
    "webp",
] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
wayland-backend = { version = "0.3.15", features = ["client_system", "dlopen", "rwh_06"] }
wayland-client = "0.31.11"
wayland-protocols = { version = "0.32.9", features = ["client"] }

[[bench]]
name = "layout_line"
harness = false
