[package]
name = "zpui-ios"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"

[lints.rust]
unexpected_cfgs = "allow"

[lints.clippy]
style = { level = "allow", priority = -1 }
dbg_macro = "deny"
todo = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"

[lib]
path = "src/zpui_ios.rs"
doctest = false

[dependencies]
zpui.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
accesskit_ios = "0.1.2"
anyhow.workspace = true
async-task.workspace = true
block2.workspace = true
dispatch2 = "0.3.1"
futures.workspace = true
image = { workspace = true, features = [
    "bmp",
    "dds",
    "exr",
    "ff",
    "gif",
    "hdr",
    "ico",
    "jpeg",
    "png",
    "pnm",
    "qoi",
    "rayon",
    "tga",
    "tiff",
    "webp",
] }
log = { workspace = true, features = ["kv_unstable_serde", "serde"] }
memmap2 = "0.9.11"
objc.workspace = true
parking_lot.workspace = true
raw-window-handle.workspace = true
uuid.workspace = true
zpui-wgpu.workspace = true
