set-option -g mouse on
set-option -s escape-time 25
set-window-option -g automatic-rename on
set-window-option -g automatic-rename-format '#{pane_current_command}'
set-window-option -g remain-on-exit on
set-option -s default-terminal zz-term
set-option -g display-time 1200
set-option -g repeat-time 650
set-window-option -u -t w:0 automatic-rename
rename-window -t w:0 explicit
split-window -d -t w:0 'exit 7'
