set-option -s focus-events on
set-option -s history-file /tmp/zz-c1-history
set-option -s prefix-timeout 250
set-option -s prompt-history-limit 3
set-option -g bell-action other
set-option -g default-size 132x43
set-option -g display-panes-time 1400
set-option -g key-table custom-c1
set-option -g visual-bell both
set-window-option -g main-pane-height 40%
set-window-option -g main-pane-width 120
set-window-option -g other-pane-height 8
set-window-option -g other-pane-width 12%
set-window-option -g tiled-layout-max-columns 2
set-window-option -g window-size largest
set-window-option -g allow-rename on
set-window-option -g allow-set-title off
