set-option -gF @cf-root "#{b:current_file}"
set-option -gF @cf-root-full "#{current_file}"
source-file compat/scenarios/source-file-current-file-child.conf
set-option -gF @cf-after-child "#{b:current_file}"
cfalias -gF @cf-alias "#{b:current_file}"
set-hook -g after-set-buffer "set-option -gF @cf-hook '#{b:current_file}'"
set-buffer -b cfbuf value
if-shell -F 1 "set-option -gF @cf-if '#{b:current_file}'"
run-shell -C "set-option -gF @cf-run '#{b:current_file}'"
