[package]
name = "zz-gpui-macros"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"
description = "Macros used by zz-gpui"

[lints.rust]
unexpected_cfgs = "allow"

[lints.clippy]
style = { level = "allow", priority = -1 }
dbg_macro = "deny"
todo = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"

[features]
inspector = []

[lib]
path = "src/zz_gpui_macros.rs"
proc-macro = true
doctest = false
test = false

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
zz-gpui = { workspace = true, features = ["inspector"] }
