[package]
name = "zpui-platform"
version = "0.1.0"
edition.workspace = true
publish = false
license = "Apache-2.0"

[lints.rust]
unexpected_cfgs = "allow"

[lints.clippy]
style = { level = "allow", priority = -1 }
dbg_macro = "deny"
todo = "deny"
declare_interior_mutable_const = "deny"
redundant_clone = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"
nonminimal_bool = "allow"

[lib]
path = "src/zpui_platform.rs"
doctest = false

[features]
default = []
bench-support = ["zpui/bench-support", "zpui-macos/bench-support", "zpui-wgpu/bench-support"]
font-kit = ["zpui-macos/font-kit"]
inspector = ["zpui/inspector"]
test-support = ["zpui/test-support", "zpui-macos/test-support", "zpui-windows/test-support", "zpui-wgpu/test-support"]
screen-capture = ["zpui/screen-capture", "zpui-macos/screen-capture", "zpui-windows/screen-capture", "zpui-linux/screen-capture"]
runtime_shaders = ["zpui-macos/runtime_shaders"]
wayland = ["zpui-linux/wayland"]
x11 = ["zpui-linux/x11"]

[[bench]]
name = "inspector_render"
harness = false
required-features = ["bench-support"]

[dependencies]
anyhow.workspace = true
zpui.workspace = true

[dev-dependencies]
criterion.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
zpui-macos.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
zpui-windows.workspace = true
zpui = { workspace = true, features = ["windows-manifest"] }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
zpui-linux.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
zpui-wgpu = { workspace = true, optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
zpui-web.workspace = true
console_error_panic_hook.workspace = true
