[package]
name = "zpui_platform"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/zpui_platform.rs"
doctest = false

[features]
default = []
bench-support = ["zpui/bench-support", "zpui_macos/bench-support", "zpui_wgpu/bench-support"]
font-kit = ["zpui_macos/font-kit"]
inspector = ["zpui/inspector"]
test-support = ["zpui/test-support", "zpui_macos/test-support", "zpui_windows/test-support", "zpui_wgpu/test-support"]
screen-capture = ["zpui/screen-capture", "zpui_macos/screen-capture", "zpui_windows/screen-capture", "zpui_linux/screen-capture"]
runtime_shaders = ["zpui_macos/runtime_shaders"]
wayland = ["zpui_linux/wayland"]
x11 = ["zpui_linux/x11"]

[[bench]]
name = "inspector_render"
harness = false
required-features = ["bench-support"]

[dependencies]
anyhow.workspace = true
zpui.workspace = true

[dev-dependencies]
criterion.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
zpui_macos.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
zpui_windows.workspace = true
zpui = { workspace = true, features = ["windows-manifest"] }

[target.'cfg(any(target_os = "linux", target_os = "freebsd"))'.dependencies]
zpui_linux.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
zpui_wgpu = { workspace = true, optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
zpui_web.workspace = true
console_error_panic_hook.workspace = true
